// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Data.Migrations
{
    [DbContext(typeof(BackendDbContext))]
    [Migration("20260414154751_fix errors")]
    partial class fixerrors
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CO2Emission")
                        .HasColumnType("int");

                    b.Property<float>("GasConsumption")
                        .HasColumnType("float");

                    b.Property<float>("MaxElectricity")
                        .HasColumnType("float");

                    b.Property<float>("MaxHeat")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<float>("OilConsumption")
                        .HasColumnType("float");

                    b.Property<int>("ProductionCost")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("Backend.Models.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageLink")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("Backend.Models.OptimizedResults", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("OptimizedResults");
                });

            modelBuilder.Entity("Backend.Models.Result", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<int>("CO2Produced")
                        .HasColumnType("int");

                    b.Property<float>("Electricity")
                        .HasColumnType("float");

                    b.Property<float>("HeatProduction")
                        .HasColumnType("float");

                    b.Property<float>("PrimaryEnergyConsumed")
                        .HasColumnType("float");

                    b.Property<float>("ProductionCost")
                        .HasColumnType("float");

                    b.Property<int?>("ResultListId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("ResultListId");

                    b.ToTable("Results");
                });

            modelBuilder.Entity("Backend.Models.ResultList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("OptimizedResultsId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeFrom")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("TimeTo")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("OptimizedResultsId");

                    b.ToTable("ResultList");
                });

            modelBuilder.Entity("Backend.Models.Source", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("ElectricityPrice")
                        .HasColumnType("float");

                    b.Property<float>("HeatDemand")
                        .HasColumnType("float");

                    b.Property<DateTime>("TimeFrom")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("TimeTo")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Sources");
                });

            modelBuilder.Entity("Backend.Models.Result", b =>
                {
                    b.HasOne("Backend.Models.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.ResultList", null)
                        .WithMany("Results")
                        .HasForeignKey("ResultListId");

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("Backend.Models.ResultList", b =>
                {
                    b.HasOne("Backend.Models.OptimizedResults", null)
                        .WithMany("ResultsForHours")
                        .HasForeignKey("OptimizedResultsId");
                });

            modelBuilder.Entity("Backend.Models.OptimizedResults", b =>
                {
                    b.Navigation("ResultsForHours");
                });

            modelBuilder.Entity("Backend.Models.ResultList", b =>
                {
                    b.Navigation("Results");
                });
#pragma warning restore 612, 618
        }
    }
}
